services:
  backend:
    image: backend:0.1
    build:
      context: ./config/django-image
    volumes:
      - ./src/django:/usr/src/app:delegated
    environment:
      DB_HOST=${DB_HOST}
      POSTGRESS_USER=${POSTGRESS_USER}
      POSTGRESS_DB=${POSTGRESS_DB}
      POSTGRESS_PASSWORD=${POSTGRESS_PASSWORD}
    ports:
      - 8000:8000
    networks:
      red:
      
  postgres:
    image: postgres:16-bullseye
    environment:
      POSTGRESS_USER=${POSTGRESS_USER}
      POSTGRESS_DB=${POSTGRESS_DB}
      POSTGRESS_PASSWORD=${POSTGRESS_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data:delegated
    ports:
       ${DB_PORT}:5432
    networks:
      red:
